/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserDashboard;

import AdminDashboard.Company_Profile;
import Config.PanelPrinter;
import Config.insertImage;
import config.dbConnector;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;


/**
 *
 * @author Elmer Rapon
 */
public class PrintingDR extends javax.swing.JFrame {

    /**
     * Creates new form PrintingDR
     */
    public PrintingDR() {
        initComponents();
    }

    
    Color orig = new Color(255,255,255);
    Color newColor =new Color(204,204,204);
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelPrint = new javax.swing.JPanel();
        CompanysLogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CompanysAddress = new javax.swing.JLabel();
        CompanysContact = new javax.swing.JLabel();
        CompanysEmail = new javax.swing.JLabel();
        DeliveryNumber = new javax.swing.JLabel();
        DRDate = new javax.swing.JLabel();
        CompanysWebsite = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        CustomersContact = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CustomersName = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        CustomersAddress = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        custID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DRTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CashName = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        GTotal = new javax.swing.JLabel();
        CompanysName = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        print = new javax.swing.JLabel();
        CompanysName1 = new javax.swing.JLabel();
        DRCode = new javax.swing.JTextField();
        GO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(null);

        PanelPrint.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelPrint.setLayout(null);

        CompanysLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CompanysLogo.setOpaque(true);
        PanelPrint.add(CompanysLogo);
        CompanysLogo.setBounds(20, 10, 270, 170);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("DELIVERY RECEIPT");
        PanelPrint.add(jLabel3);
        jLabel3.setBounds(880, 20, 250, 30);

        CompanysAddress.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CompanysAddress.setText("ADDRESS");
        PanelPrint.add(CompanysAddress);
        CompanysAddress.setBounds(300, 40, 560, 30);

        CompanysContact.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CompanysContact.setText("CONTACT NUMBER");
        PanelPrint.add(CompanysContact);
        CompanysContact.setBounds(300, 70, 390, 30);

        CompanysEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CompanysEmail.setText("EMAIL");
        PanelPrint.add(CompanysEmail);
        CompanysEmail.setBounds(300, 100, 390, 30);

        DeliveryNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelPrint.add(DeliveryNumber);
        DeliveryNumber.setBounds(970, 60, 160, 30);

        DRDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        PanelPrint.add(DRDate);
        DRDate.setBounds(970, 90, 160, 30);

        CompanysWebsite.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CompanysWebsite.setText("WEBSITE");
        PanelPrint.add(CompanysWebsite);
        CompanysWebsite.setBounds(300, 130, 390, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("DR NO.:");
        PanelPrint.add(jLabel13);
        jLabel13.setBounds(900, 60, 70, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("DATE:");
        PanelPrint.add(jLabel14);
        jLabel14.setBounds(910, 90, 60, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DELIVERED TO:");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel11);
        jLabel11.setBounds(0, 0, 760, 30);

        CustomersContact.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CustomersContact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(CustomersContact);
        CustomersContact.setBounds(210, 80, 510, 40);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("CUSTOMER NAME:");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(30, 50, 180, 30);

        CustomersName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CustomersName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(CustomersName);
        CustomersName.setBounds(210, 40, 510, 40);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("ADDRESS:");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(30, 130, 180, 30);

        CustomersAddress.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CustomersAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(CustomersAddress);
        CustomersAddress.setBounds(210, 120, 510, 40);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("CONTACT NUMBER:");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(30, 90, 180, 30);

        PanelPrint.add(jPanel3);
        jPanel3.setBounds(10, 190, 760, 190);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("CUSTOMER ID:");
        PanelPrint.add(jLabel8);
        jLabel8.setBounds(840, 120, 130, 30);

        custID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        PanelPrint.add(custID);
        custID.setBounds(970, 120, 160, 30);

        DRTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DRTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(DRTable);

        PanelPrint.add(jScrollPane1);
        jScrollPane1.setBounds(10, 390, 1120, 280);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("CHECKED AND CERTIFIED BY:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 10, 360, 30);

        CashName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CashName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CashName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel4.add(CashName);
        CashName.setBounds(10, 50, 400, 30);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Received the above merchandise in good order and condition:");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(460, 10, 480, 20);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Signature over Printed Name/Date");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(10, 80, 400, 20);

        jLabel26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel26);
        jLabel26.setBounds(570, 50, 550, 30);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Customer's Signature over Printed Name/Date");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(570, 80, 550, 20);

        PanelPrint.add(jPanel4);
        jPanel4.setBounds(10, 720, 1120, 110);

        GTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        GTotal.setForeground(new java.awt.Color(255, 0, 0));
        GTotal.setText(" GRAND TOTAL:");
        GTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelPrint.add(GTotal);
        GTotal.setBounds(820, 670, 310, 30);

        CompanysName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        CompanysName.setText("COMPANY'S NAME");
        PanelPrint.add(CompanysName);
        CompanysName.setBounds(300, 10, 390, 30);

        jPanel1.add(PanelPrint);
        PanelPrint.setBounds(10, 50, 1140, 850);

        back.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("BACK");
        back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(490, 930, 160, 30);

        print.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        print.setForeground(new java.awt.Color(255, 0, 0));
        print.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print.setText("PRINT");
        print.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        print.setOpaque(true);
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printMouseExited(evt);
            }
        });
        jPanel1.add(print);
        print.setBounds(490, 900, 160, 30);

        CompanysName1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CompanysName1.setText("ENTER DR NUMBER TO PRINT");
        jPanel1.add(CompanysName1);
        CompanysName1.setBounds(10, 10, 270, 30);

        DRCode.setBackground(new java.awt.Color(240, 240, 240));
        DRCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(DRCode);
        DRCode.setBounds(280, 10, 200, 30);

        GO.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        GO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GO.setText("GO");
        GO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GO.setOpaque(true);
        GO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GOMouseExited(evt);
            }
        });
        jPanel1.add(GO);
        GO.setBounds(490, 10, 60, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOMouseClicked
        // TODO add your handling code here:
       dbConnector db = new dbConnector();
       insertImage im = new insertImage();
       Company_Profile cp = new Company_Profile();

       String sql = "SELECT * FROM companyprofile";
       ResultSet rs;
       try {
           rs = db.getData(sql);

           if (rs.next()) {
               String comID = rs.getString("CP_ID");

               if (comID != null && !comID.isEmpty()) {
                   CompanysName.setText(rs.getString("Company_Name"));
                   CompanysContact.setText(rs.getString("Contact_Number"));
                   CompanysEmail.setText(rs.getString("Email_Address"));
                   CompanysWebsite.setText(rs.getString("Website"));

                   String photoPath = rs.getString("Company_Logo");
                   if (photoPath != null && !photoPath.isEmpty()) {
                       CompanysLogo.setIcon(im.ResizeImage(photoPath, null, CompanysLogo));
                       cp.oldPath = photoPath;
                       cp.path = photoPath;
                       cp.destination = photoPath;
                   } else {
                       // If no photo is available, clear the icon and paths
                       CompanysLogo.setIcon(null);
                       cp.oldPath = "";
                       cp.path = "";
                       cp.destination = "";
                   }
               }
           } else {
               // No rows found
               JOptionPane.showMessageDialog(null, "NO COMPANY'S DETAILS FOUND", "Error", JOptionPane.ERROR_MESSAGE);
               CompanysName.setText("");
               CompanysContact.setText("");
               CompanysEmail.setText("");
               CompanysWebsite.setText("");
           }
       } catch (SQLException ex) {
           Logger.getLogger(PrintingDR.class.getName()).log(Level.SEVERE, null, ex);
       }
       
       String add = "SELECT * FROM business_address";
       ResultSet res;
       try {
           res = db.getData(add);

           if (res.next()) {
               String addID = res.getString("Add_ID");

               if (addID != null && !addID.isEmpty()) {
                   String purok = res.getString("Purok");
                   String brgy = res.getString("Baranggay");
                   String municipality = res.getString("Municipality");   
                   String zipCode = res.getString("ZIP_Code");
                   String province = res.getString("Province"); 
                   String country = res.getString("Country");                   
                   CompanysAddress.setText(purok +", " + brgy + ", "+ municipality +", " +zipCode +", " + province +", " +country);
               }
           } else {
               // No rows found
               JOptionPane.showMessageDialog(null, "NO COMPANY'S DETAILS FOUND", "Error", JOptionPane.ERROR_MESSAGE);
               CompanysAddress.setText("");
           }
       } catch (SQLException ex) {
           Logger.getLogger(PrintingDR.class.getName()).log(Level.SEVERE, null, ex);
       }
//-------------------------------------------------------------------------------------------------------------------------------------------------------------------
        try {
        String code = DRCode.getText();

        if (code.isEmpty()) {
            JOptionPane.showMessageDialog(null, "INPUT DR NUMBER FIRST", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String sqel = "SELECT " +
                         "product_information.P_Name, product_information.P_Flavor, product_information.P_Price, product_information.P_Net, product_information.P_Unit, " +
                         "SUM(orderform.OrderQuantity) AS TotalQuantity, SUM(orderform.O_TotalAmount) AS TotalAmount, " +
                         "lmer_table.lmer_fname, lmer_table.lmer_lname, drgenerator.DeliveryDate, drgenerator.CustomerID, " +
                         "customerinfo.CustomerName, customerinfo.CustomerContactNo, customeradd.CustPurok, customeradd.CustBarangay, " +
                         "customeradd.CustMunicipal, customeradd.CustProvince, customeradd.CustCountry " +
                         "FROM drgenerator " +
                         "JOIN orderform ON drgenerator.DRNo = orderform.DRNumber " +
                         "JOIN product_information ON orderform.ProductID = product_information.P_Code " +
                         "JOIN lmer_table ON drgenerator.CashierID = lmer_table.lmer_ID " +
                         "JOIN customerinfo ON drgenerator.CustomerID = customerinfo.CustomerID " +
                         "JOIN customeradd ON customerinfo.CustomerAddress = customeradd.customAddNo " +
                         "WHERE drgenerator.DRNo = ? " +
                         "GROUP BY product_information.P_Name, product_information.P_Flavor, product_information.P_Price, product_information.P_Net, product_information.P_Unit, " +
                         "lmer_table.lmer_fname, lmer_table.lmer_lname, drgenerator.DeliveryDate, drgenerator.CustomerID, " +
                         "customerinfo.CustomerName, customerinfo.CustomerContactNo, customeradd.CustPurok, customeradd.CustBarangay, " +
                         "customeradd.CustMunicipal, customeradd.CustProvince, customeradd.CustCountry";

            PreparedStatement ps = db.getConnection().prepareStatement(sqel);
            ps.setString(1, code);
            ResultSet rees = ps.executeQuery();

            // Set table headers
            String[] columnNames = {"ITEM DESCRIPTION", "PRICE", "QUANTITY", "AMOUNT"};
            DefaultTableModel model = new DefaultTableModel(columnNames, 0);
            DRTable.setModel(model);
            model.setRowCount(0); // Clear existing rows

            // Customize header appearance
            JTableHeader header = DRTable.getTableHeader();
            header.setBackground(Color.GRAY);
            header.setForeground(Color.BLACK);
            header.setFont(new Font("Arial", Font.BOLD, 14));
            header.setPreferredSize(new Dimension(header.getPreferredSize().width, 40)); // Adjust header height

            // Customize row appearance
            DRTable.setRowHeight(30); // Adjust row height
            DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                    Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    c.setBackground(row % 2 == 0 ? Color.LIGHT_GRAY : Color.WHITE); // Alternating row colors
                    return c;
                }
            };
            for (int i = 0; i < DRTable.getColumnCount(); i++) {
                DRTable.getColumnModel().getColumn(i).setCellRenderer(renderer);
            }

            int grandTotal = 0;

            NumberFormat formatter = NumberFormat.getNumberInstance(Locale.US);
            formatter.setMinimumFractionDigits(2);
            formatter.setMaximumFractionDigits(2);

            if (rees.next()) {
                do {
                    String productName = rees.getString("P_Name");
                    String productFlavor = rees.getString("P_Flavor");
                    String productNetWeight = rees.getString("P_Net");
                    String productUnit = rees.getString("P_Unit");

                    String custPurok = rees.getString("CustPurok");
                    String custBrgy = rees.getString("CustBarangay");
                    String custMuni = rees.getString("CustMunicipal");
                    String custProv = rees.getString("CustProvince");
                    String custCount = rees.getString("CustCountry");

                    String custName = rees.getString("CustomerName");
                    String custAdd = custPurok + ", " + custBrgy + ", " + custMuni + ", " + custProv + ", " + custCount;
                    String custContact = rees.getString("CustomerContactNo");
                    String customID = rees.getString("CustomerID");

                    int productPrice = rees.getInt("P_Price");
                    int quantity = rees.getInt("TotalQuantity");
                    int totalAmount = rees.getInt("TotalAmount");

                    String TotalAmount = formatter.format(totalAmount);

                    String cashierName = rees.getString("lmer_fname") + " " + rees.getString("lmer_lname");
                    Date deliveryDate = rees.getDate("DeliveryDate");

                    grandTotal += totalAmount;
                    GTotal.setText("GRAND TOTAL: ₱" + formatter.format(grandTotal));

                    CustomersName.setText(custName);
                    CustomersAddress.setText(custAdd);
                    CustomersContact.setText(custContact);
                    custID.setText(customID);
                    DeliveryNumber.setText(code);
                    CashName.setText(cashierName);
                    DRDate.setText(deliveryDate.toString());

                    model.addRow(new Object[]{
                        productName + " " + productFlavor + " " + productNetWeight +productUnit,
                        formatter.format(productPrice),
                        quantity,
                        TotalAmount
                    });
                } while (rees.next());
            } else {
                // No rows found
                JOptionPane.showMessageDialog(null, "NO PENDING DR FOUND", "Error", JOptionPane.ERROR_MESSAGE);
                CustomersName.setText("");
                CustomersAddress.setText("");
                CustomersContact.setText("");
                custID.setText("");
                DeliveryNumber.setText("");
                CashName.setText("");
                DRDate.setText("");
                GTotal.setText("");
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(PrintingDR.class.getName()).log(Level.SEVERE, null, ex);
        System.out.println("SQL Exception: " + ex.getMessage());
    }
    }//GEN-LAST:event_GOMouseClicked

    private void GOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOMouseEntered
        // TODO add your handling code here:
        GO.setBackground(newColor);
    }//GEN-LAST:event_GOMouseEntered

    private void GOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOMouseExited
        // TODO add your handling code here:
        GO.setBackground(orig);
    }//GEN-LAST:event_GOMouseExited

    private void printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseEntered
        // TODO add your handling code here:
        print.setBackground(newColor);
        
    }//GEN-LAST:event_printMouseEntered

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setBackground(newColor);
    }//GEN-LAST:event_backMouseEntered

    private void printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseExited
        // TODO add your handling code here:
        print.setBackground(orig);
    }//GEN-LAST:event_printMouseExited

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        back.setBackground(orig);
    }//GEN-LAST:event_backMouseExited

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        // TODO add your handling code here:
        JPanel myPanel = new JPanel();
        // Add components to myPanel as needed
        PanelPrinter printer = new PanelPrinter(PanelPrint);
        printer.printPanel();
        
    }//GEN-LAST:event_printMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintingDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintingDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintingDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintingDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintingDR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CashName;
    private javax.swing.JLabel CompanysAddress;
    private javax.swing.JLabel CompanysContact;
    private javax.swing.JLabel CompanysEmail;
    private javax.swing.JLabel CompanysLogo;
    private javax.swing.JLabel CompanysName;
    private javax.swing.JLabel CompanysName1;
    private javax.swing.JLabel CompanysWebsite;
    private javax.swing.JLabel CustomersAddress;
    private javax.swing.JLabel CustomersContact;
    private javax.swing.JLabel CustomersName;
    private javax.swing.JTextField DRCode;
    private javax.swing.JLabel DRDate;
    private javax.swing.JTable DRTable;
    private javax.swing.JLabel DeliveryNumber;
    private javax.swing.JLabel GO;
    private javax.swing.JLabel GTotal;
    private javax.swing.JPanel PanelPrint;
    private javax.swing.JLabel back;
    private javax.swing.JLabel custID;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel print;
    // End of variables declaration//GEN-END:variables
}
