
package UserDashboard;
import config.dbConnector;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JDesktopPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Elmer Rapon
 */
public class transaction extends javax.swing.JInternalFrame {    
    
    public transaction() throws SQLException {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        
    nnew.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        newProduct prod = new newProduct();
        JDesktopPane desktopPane = (JDesktopPane) getParent();
        desktopPane.add(prod);
        prod.remove.setEnabled(false);
        prod.upload.setEnabled(true);
        prod.setVisible(true);
        setVisible(false);
    }
    });
    
    op.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        Output op = new Output();
        JDesktopPane desktopPane = (JDesktopPane) getParent();
        desktopPane.add(op);
        op.setVisible(true);
        setVisible(false);
    }
    });
    
    delRe.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        DRTransactions drT = new DRTransactions();
        JDesktopPane desktopPane = (JDesktopPane) getParent();
        desktopPane.add(drT);
        drT.setVisible(true);
        setVisible(false);
    }
    });
    
    ot.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        DamageProducts damage = new DamageProducts();
        JDesktopPane desktopPane = (JDesktopPane) getParent();
        desktopPane.add(damage);
        damage.setVisible(true);
        setVisible(false);
    }
    });
    
    getTotalSoldProducts();
    
    }   
   

    Color navcolor = new Color (153,153,153);
    Color headcolor = new Color (153,153,153);
    Color bodycolor =new Color (102,102,102);;
    Color transColor = new Color (240,240,240);
    Color newBack = new Color (204,204,204);
    Color label = new Color (0,102,102);
    
    
    public static void getTotalSoldProducts() {
        try {
            dbConnector db = new dbConnector();
            String sql = "SELECT SUM(OrderQuantity) as TOTALSOLD, SUM(O_TotalAmount) as TOTALAMOUNT FROM orderform WHERE OrderStatus = 'DELIVERED'";
            ResultSet resultSet = db.getData(sql);
            if (resultSet.next()) {
                int totalSoldQuantity = resultSet.getInt("TOTALSOLD");
                double AccReceive = resultSet.getDouble("TOTALAMOUNT");          
                NumberFormat numberFormat = NumberFormat.getNumberInstance(Locale.US);
                String TotalSold = numberFormat.format(totalSoldQuantity);
                String AcccReceive = numberFormat.format(AccReceive);
                
                TotalProductSold.setText(TotalSold);
                sales.setText("₱" +AcccReceive);
            } else {
                TotalProductSold.setText("0");
                sales.setText("0");
            }
            
            
            String query = "SELECT SUM(DamageQuantity) as TOTALDAMAGE FROM damageproduct";
                        ResultSet result = db.getData(query);
                        if (result.next()) {
                            int quan = result.getInt("TOTALDAMAGE");
                            
                        NumberFormat numberFormat = NumberFormat.getNumberInstance(Locale.US);
                        String TotalDamage = numberFormat.format(quan);

                            totalDamage.setText(TotalDamage);
                        } else {
                            totalDamage.setText("0");
                        }
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Anew = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        NumProd = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        sales = new javax.swing.JLabel();
        dr = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TotalProductSold = new javax.swing.JLabel();
        other = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totalDamage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nnew = new javax.swing.JLabel();
        op = new javax.swing.JLabel();
        delRe = new javax.swing.JLabel();
        ot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        Anew.setBackground(new java.awt.Color(0, 102, 51));
        Anew.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Anew.setForeground(new java.awt.Color(181, 181, 181));
        Anew.setToolTipText("");
        Anew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AnewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AnewMouseExited(evt);
            }
        });
        Anew.setLayout(null);

        jLabel11.setBackground(new java.awt.Color(50, 150, 122));
        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" Total Product Available");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(255, 255, 255)));
        jLabel11.setOpaque(true);
        Anew.add(jLabel11);
        jLabel11.setBounds(0, 0, 320, 40);

        NumProd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NumProd.setForeground(new java.awt.Color(255, 255, 255));
        NumProd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NumProd.setText("500");
        Anew.add(NumProd);
        NumProd.setBounds(10, 170, 300, 40);

        jPanel1.add(Anew);
        Anew.setBounds(50, 160, 320, 210);

        update.setBackground(new java.awt.Color(0, 102, 51));
        update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(17, 105, 105), null, null));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(50, 150, 122));
        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Accounts Receivable");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(255, 255, 255)));
        jLabel4.setOpaque(true);
        update.add(jLabel4);
        jLabel4.setBounds(0, 0, 320, 40);

        sales.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sales.setForeground(new java.awt.Color(255, 255, 255));
        sales.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sales.setText("345");
        update.add(sales);
        sales.setBounds(10, 170, 300, 40);

        jPanel1.add(update);
        update.setBounds(390, 160, 320, 210);

        dr.setBackground(new java.awt.Color(0, 102, 51));
        dr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(17, 105, 105), null, null));
        dr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                drMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                drMouseExited(evt);
            }
        });
        dr.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(50, 150, 122));
        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("  Total Product Sold");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(255, 255, 255)));
        jLabel5.setOpaque(true);
        dr.add(jLabel5);
        jLabel5.setBounds(0, 0, 320, 40);

        TotalProductSold.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TotalProductSold.setForeground(new java.awt.Color(255, 255, 255));
        TotalProductSold.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TotalProductSold.setText("378");
        dr.add(TotalProductSold);
        TotalProductSold.setBounds(10, 180, 300, 40);

        jPanel1.add(dr);
        dr.setBounds(50, 390, 320, 220);

        other.setBackground(new java.awt.Color(0, 102, 51));
        other.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(17, 105, 105), null, null));
        other.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                otherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                otherMouseExited(evt);
            }
        });
        other.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(50, 150, 122));
        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Total Expired/BO Products ");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(255, 255, 255)));
        jLabel2.setOpaque(true);
        other.add(jLabel2);
        jLabel2.setBounds(0, 0, 320, 40);

        totalDamage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalDamage.setForeground(new java.awt.Color(255, 255, 255));
        totalDamage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalDamage.setText("746");
        other.add(totalDamage);
        totalDamage.setBounds(10, 180, 300, 40);

        jPanel1.add(other);
        other.setBounds(390, 390, 320, 220);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 150, 122));
        jLabel1.setText("TRANSACTIONS");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 30, 710, 40);

        nnew.setBackground(new java.awt.Color(0, 102, 102));
        nnew.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        nnew.setForeground(new java.awt.Color(255, 255, 255));
        nnew.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE/icons8-plus-sign-20.png"))); // NOI18N
        nnew.setText("New");
        nnew.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nnew.setOpaque(true);
        nnew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nnewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nnewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nnewMouseExited(evt);
            }
        });
        jPanel1.add(nnew);
        nnew.setBounds(50, 100, 120, 40);

        op.setBackground(new java.awt.Color(0, 102, 102));
        op.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        op.setForeground(new java.awt.Color(255, 255, 255));
        op.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE/icons8-input-20.png"))); // NOI18N
        op.setText(" Output");
        op.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        op.setOpaque(true);
        op.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                opMouseExited(evt);
            }
        });
        jPanel1.add(op);
        op.setBounds(230, 100, 120, 40);

        delRe.setBackground(new java.awt.Color(0, 102, 102));
        delRe.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        delRe.setForeground(new java.awt.Color(255, 255, 255));
        delRe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delRe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE/icons8-receipt-20.png"))); // NOI18N
        delRe.setText(" DR");
        delRe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delRe.setOpaque(true);
        delRe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delReMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delReMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                delReMouseExited(evt);
            }
        });
        jPanel1.add(delRe);
        delRe.setBounds(410, 100, 120, 40);

        ot.setBackground(new java.awt.Color(0, 102, 102));
        ot.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        ot.setForeground(new java.awt.Color(236, 5, 7));
        ot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE/icons8-cancel-20 (1).png"))); // NOI18N
        ot.setText("Damage");
        ot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ot.setOpaque(true);
        ot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                otMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                otMouseExited(evt);
            }
        });
        jPanel1.add(ot);
        ot.setBounds(590, 100, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnewMouseEntered

    }//GEN-LAST:event_AnewMouseEntered

    private void AnewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnewMouseExited

    }//GEN-LAST:event_AnewMouseExited

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered

    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited

    }//GEN-LAST:event_updateMouseExited

    private void drMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drMouseEntered
        // TODO add your handling code here:

        
    }//GEN-LAST:event_drMouseEntered

    private void drMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_drMouseExited

    private void otherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherMouseEntered
        // TODO add your handling code here:
 
    }//GEN-LAST:event_otherMouseEntered

    private void otherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_otherMouseExited

    private void nnewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nnewMouseEntered
        // TODO add your handling code here:
        nnew.setBackground(newBack);
        
    }//GEN-LAST:event_nnewMouseEntered

    private void nnewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nnewMouseExited
        // TODO add your handling code here:
        nnew.setBackground(label);
    }//GEN-LAST:event_nnewMouseExited

    private void opMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opMouseEntered
        // TODO add your handling code here:
        op.setBackground(newBack); 
    }//GEN-LAST:event_opMouseEntered

    private void opMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opMouseExited
        // TODO add your handling code here:
        op.setBackground(label);
    }//GEN-LAST:event_opMouseExited

    private void delReMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delReMouseEntered
        // TODO add your handling code here:
        delRe.setBackground(newBack);
    }//GEN-LAST:event_delReMouseEntered

    private void delReMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delReMouseExited
        // TODO add your handling code here:
        delRe.setBackground(label);    
    }//GEN-LAST:event_delReMouseExited

    private void otMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otMouseEntered
        // TODO add your handling code here:
        ot.setBackground(newBack);   
    }//GEN-LAST:event_otMouseEntered

    private void otMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otMouseExited
        // TODO add your handling code here:
        ot.setBackground(label);    
    }//GEN-LAST:event_otMouseExited

    private void nnewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nnewMouseClicked
   
    }//GEN-LAST:event_nnewMouseClicked

    private void delReMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delReMouseClicked
        // TODO add your handling code here:              
    }//GEN-LAST:event_delReMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Anew;
    private static javax.swing.JLabel NumProd;
    private static javax.swing.JLabel TotalProductSold;
    private javax.swing.JLabel delRe;
    private javax.swing.JPanel dr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nnew;
    private javax.swing.JLabel op;
    private javax.swing.JLabel ot;
    private javax.swing.JPanel other;
    private static javax.swing.JLabel sales;
    private static javax.swing.JLabel totalDamage;
    private javax.swing.JPanel update;
    // End of variables declaration//GEN-END:variables
}
