/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reports;

import Config.insertImage;
import static UserDashboard.Output.checkQuantity;
import UserDashboard.newProduct;
import config.dbConnector;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Elmer Rapon
 */
public class ViewProducts extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewProducts
     */
    public ViewProducts() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
       CountProduct();
    }

    
    Color orig = new Color(240,240,240);
    Color newColor =new Color(204,204,204);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void CountProduct() {
        try {
            dbConnector db = new dbConnector();
            String sql = "SELECT COUNT(P_Code) AS count FROM product_information";
            ResultSet rs = db.getData(sql);

            if (rs.next()) {
                int count = rs.getInt("count");
                num.setText(Integer.toString(count));
            } else {
                num.setText("0");
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(ViewProducts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    

    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        OLogo = new javax.swing.JLabel();
        OPrice = new javax.swing.JLabel();
        OName = new javax.swing.JLabel();
        OFlavor = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        OCode = new javax.swing.JTextField();
        ok = new javax.swing.JLabel();
        quantity = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        num = new javax.swing.JLabel();

        jPanel2.setLayout(null);

        OLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        OLogo.setOpaque(true);
        jPanel2.add(OLogo);
        OLogo.setBounds(450, 60, 270, 270);

        OPrice.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        OPrice.setForeground(new java.awt.Color(50, 150, 122));
        OPrice.setText("Price: ");
        OPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        OPrice.setOpaque(true);
        jPanel2.add(OPrice);
        OPrice.setBounds(30, 420, 440, 30);

        OName.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        OName.setForeground(new java.awt.Color(50, 150, 122));
        OName.setText("Name:");
        OName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        OName.setOpaque(true);
        jPanel2.add(OName);
        OName.setBounds(30, 340, 440, 30);

        OFlavor.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        OFlavor.setForeground(new java.awt.Color(50, 150, 122));
        OFlavor.setText("Flavor");
        OFlavor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        OFlavor.setOpaque(true);
        jPanel2.add(OFlavor);
        OFlavor.setBounds(30, 380, 440, 30);

        status.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        status.setForeground(new java.awt.Color(50, 150, 122));
        status.setText("Status:");
        status.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        status.setOpaque(true);
        jPanel2.add(status);
        status.setBounds(30, 500, 440, 30);

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(50, 150, 122));
        jLabel16.setText("Enter Product Code: ");
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, 210, 270, 30);

        OCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OCodeActionPerformed(evt);
            }
        });
        jPanel2.add(OCode);
        OCode.setBounds(20, 250, 190, 40);

        ok.setBackground(new java.awt.Color(255, 255, 255));
        ok.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        ok.setForeground(new java.awt.Color(255, 0, 51));
        ok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ok.setText("Ok");
        ok.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ok.setOpaque(true);
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okMouseExited(evt);
            }
        });
        jPanel2.add(ok);
        ok.setBounds(220, 250, 90, 40);

        quantity.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        quantity.setForeground(new java.awt.Color(50, 150, 122));
        quantity.setText("Quantity:");
        quantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        quantity.setOpaque(true);
        jPanel2.add(quantity);
        quantity.setBounds(30, 460, 440, 30);

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(50, 150, 122));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE/icons8-list-30.png"))); // NOI18N
        jLabel15.setText("PRODUCT DETAILS");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 10, 750, 40);

        jPanel1.setBackground(new java.awt.Color(50, 150, 122));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>TOTAL NUMBER OF PRODUCTS</html>");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 130, 70);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(120, 0, 10, 90);

        num.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        num.setForeground(new java.awt.Color(255, 0, 0));
        num.setText("jLabel2");
        jPanel1.add(num);
        num.setBounds(130, 30, 160, 40);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(20, 70, 300, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OCodeActionPerformed

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked

        dbConnector dbc = new dbConnector();
        newProduct np = new newProduct();
        insertImage im = new insertImage();

        try {
            String code = OCode.getText();

            if (code.isEmpty()) {
                JOptionPane.showMessageDialog(null, "INPUT PRODUCT CODE FIRST", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                String sql = "SELECT * FROM product_information WHERE P_Code = '" + code + "'";
                ResultSet rs = dbc.getData(sql);

                if (rs.next()) {
                    int productCode = rs.getInt("P_Code");

                    if (code.equals(String.valueOf(productCode))) {
                        int productPrice = rs.getInt("P_Price");
                        int quan = checkQuantity(productCode); // get the quantity for the specific product

                        String statu;
                        if (quan > 50) {
                            statu = "IN STOCK";
                        } else if (quan > 0) {
                            statu = "LOW STOCK";
                        } else {
                            statu = "NO STOCK";
                        }

                        OName.setText("Name: " + rs.getString("P_Name"));
                        OFlavor.setText("Flavor: " + rs.getString("P_Flavor"));
                        OPrice.setText("Price: " + productPrice);
                        quantity.setText("Quantity: " + quan);
                        status.setText("Status: " + statu);

                        String photoPath = rs.getString("P_Photo");
                        if (photoPath != null && !photoPath.isEmpty()) {
                            OLogo.setIcon(im.ResizeImage(photoPath, null, OLogo));
                            np.oldPath = photoPath;
                            np.path = photoPath;
                            np.destination = photoPath;
                        } else {
                            // If no photo is available, clear the icon and paths
                            OLogo.setIcon(null);
                            np.oldPath = "";
                            np.path = "";
                            np.destination = "";
                        }
                    }
                } else {
                    // No rows found
                    JOptionPane.showMessageDialog(null, "NO PRODUCT FOUND", "Error", JOptionPane.ERROR_MESSAGE);
                    OName.setText("");
                    OFlavor.setText("");
                    OPrice.setText("");
                    quantity.setText("");
                    status.setText("");
                    OLogo.setIcon(null); // Clear the icon
                    np.oldPath = "";
                    np.path = "";
                    np.destination = "";
                }
            }
        } catch (SQLException ex) {
            System.out.println("Invalid Connection: " + ex.getMessage());
        }
    }//GEN-LAST:event_okMouseClicked

    private void okMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseEntered
        // TODO add your handling code here:
        ok.setBackground(newColor);
    }//GEN-LAST:event_okMouseEntered

    private void okMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseExited
        // TODO add your handling code here:
        ok.setBackground(orig);
    }//GEN-LAST:event_okMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OCode;
    public javax.swing.JLabel OFlavor;
    public javax.swing.JLabel OLogo;
    public javax.swing.JLabel OName;
    public javax.swing.JLabel OPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel num;
    private javax.swing.JLabel ok;
    public javax.swing.JLabel quantity;
    public javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
