/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminDashboard;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Elmer Rapon
 */
public class AdminProfile extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminProfile
     */
    public AdminProfile() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    Color orig = new Color(50,150,122);
    Color newColor =new Color(204,204,204);
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        u_accountstat = new javax.swing.JLabel();
        u_email = new javax.swing.JLabel();
        u_fullname = new javax.swing.JLabel();
        up = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        u_username = new javax.swing.JLabel();
        u_position = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(50, 150, 122));
        jPanel1.setLayout(null);

        u_accountstat.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        u_accountstat.setForeground(new java.awt.Color(255, 255, 255));
        u_accountstat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(u_accountstat);
        u_accountstat.setBounds(300, 330, 430, 30);

        u_email.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        u_email.setForeground(new java.awt.Color(255, 255, 255));
        u_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(u_email);
        u_email.setBounds(300, 300, 430, 30);

        u_fullname.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        u_fullname.setForeground(new java.awt.Color(255, 255, 255));
        u_fullname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(u_fullname);
        u_fullname.setBounds(300, 270, 430, 30);

        up.setBackground(new java.awt.Color(50, 150, 122));
        up.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        up.setForeground(new java.awt.Color(255, 255, 255));
        up.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        up.setText("UPDATE?");
        up.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        up.setOpaque(true);
        up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                upMouseExited(evt);
            }
        });
        jPanel1.add(up);
        up.setBounds(310, 490, 170, 40);

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EMAIL:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 300, 110, 30);

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NAME:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 270, 110, 30);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE/icons8-user-100.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 30, 200, 100);

        u_username.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        u_username.setForeground(new java.awt.Color(255, 255, 255));
        u_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(u_username);
        u_username.setBounds(300, 130, 200, 20);

        u_position.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        u_position.setForeground(new java.awt.Color(255, 255, 255));
        u_position.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(u_position);
        u_position.setBounds(300, 160, 200, 20);

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ACCOUNT STATUS: ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 330, 220, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upMouseClicked
        // TODO add your handling code here:
        UsersAccount us = new UsersAccount();
        us.setVisible(true);
        this.dispose();
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (parentFrame instanceof admin) {
            admin ad = (admin) parentFrame;
            ad.setVisible(false);
            ad.AdminDesktop.setVisible(false);
            ad.dispose();
        }
    
    }//GEN-LAST:event_upMouseClicked

    private void upMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upMouseEntered
        // TODO add your handling code here:
        up.setBackground(newColor);
    }//GEN-LAST:event_upMouseEntered

    private void upMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upMouseExited
        // TODO add your handling code here:
        up.setBackground(orig);
    }//GEN-LAST:event_upMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel u_accountstat;
    public javax.swing.JLabel u_email;
    public javax.swing.JLabel u_fullname;
    public javax.swing.JLabel u_position;
    public javax.swing.JLabel u_username;
    private javax.swing.JLabel up;
    // End of variables declaration//GEN-END:variables
}
