/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SignUp_LogIn;

import AdminDashboard.admin;
import Config.session;
import static SignUp_LogIn.SignUp.hashPass;
import UserDashboard.user;
import config.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Elmer Rapon
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }
    
    public static String surnam;
    public static String names;
    public static String status;
    public static String type;
    public static String l_username;
    public static String emiel;
    public static String passw;
    
     public static String getCashierID() {
        String cashierID = null;
        // Retrieve the cashier ID using the logged-in user's username and password
        session ss = session.getInstance();
        String username = ss.getUsername();
        String email = ss.getEmail();
        
        cashierID = getAccountID(username, email);

        return cashierID;
    }

    public static String getAccountID(String username, String email) {
            String cashierID = null;
            dbConnector connector = new dbConnector();
            try {
                String query = "SELECT lmer_ID FROM lmer_table WHERE lmer_uname = '" + username + "' AND lmer_email = '" + email + "'";
                ResultSet resultSet = connector.getData(query);
                if (resultSet.next()) {
                    cashierID = resultSet.getString("lmer_ID");
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid username or email");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Database Connection Error!");
            }
            return cashierID;
        }

    
    public static boolean loginAcc(String uname, String pass){
        
        dbConnector connector = new dbConnector();
   
        try{
            String query = "SELECT * FROM lmer_table  WHERE lmer_uname = '" + uname + "' AND lmer_pass = '" + pass + "' AND lmer_stat = 'Active'";
            ResultSet resultSet = connector.getData(query);       
            if(resultSet.next()){               
                passw = resultSet.getString("lmer_pass");
                emiel = resultSet.getString("lmer_email");
                l_username = resultSet.getString("lmer_uname");
                status = resultSet.getString("lmer_stat");
                type = resultSet.getString("lmer_acc");
                names = resultSet.getString("lmer_fname");
                surnam = resultSet.getString("lmer_lname");
                session ss = session.getInstance();
                ss.setId(resultSet.getInt("lmer_ID"));
                ss.setFname(resultSet.getString("lmer_fname"));
                ss.setLname(resultSet.getString("lmer_lname"));
                ss.setEmail(resultSet.getString("lmer_email"));
                ss.setUsername(resultSet.getString("lmer_uname"));
                ss.setPosition(resultSet.getString("lmer_acc"));
                ss.setStatus(resultSet.getString("lmer_stat"));
                  
                return true;
            }else{
                return false; 
            }
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Database Connection Error!");
            return false;
        }

    }
    public static boolean checkAdmin(String user){
        dbConnector connect = new dbConnector();
        try{
            String query = "SELECT * FROM lmer_table WHERE lmer_uname = '" +user+"' AND lmer_acc = 'Manager'";
            ResultSet resultSet = connect.getData(query);
            return resultSet.next();
        }catch(SQLException ex){
            System.out.println("" + ex);
            return false;
    }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        logIn = new javax.swing.JButton();
        username = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICTURE/INVENTORY__1_-removebg-preview_1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 10, 280, 220);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Click here!");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 630, 80, 24);

        password.setBackground(new java.awt.Color(204, 204, 204));
        password.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(password);
        password.setBounds(110, 410, 330, 40);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Username");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 260, 130, 24);

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 370, 140, 24);

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel5.setText("Doesn't have an account yet?");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 610, 220, 24);

        check.setText("Show Password");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jPanel1.add(check);
        check.setBounds(200, 460, 170, 20);

        logIn.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        logIn.setForeground(new java.awt.Color(255, 0, 51));
        logIn.setText("LOG IN");
        logIn.setToolTipText("");
        logIn.setActionCommand("");
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });
        jPanel1.add(logIn);
        logIn.setBounds(200, 520, 150, 40);

        username.setBackground(new java.awt.Color(204, 204, 204));
        username.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(username);
        username.setBounds(110, 300, 330, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        SignUp su = new SignUp();
        su.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed
        // TODO add your handling code here:
        String pass = hashPass(password.getText());  
        if(loginAcc(username.getText(), pass)){
            
            if(!status.equals("Active")){
                JOptionPane.showMessageDialog(null, "In-Active Account, please notify the Manager");
            }else{
            if(type.equals("Manager")){
                admin ads = new admin();;
                ads.setVisible(true);
                this.dispose();
            }else if(type.equals("Inventory-In-Charge")){
                user usr = new user();
                usr.setVisible(true);
                this.dispose();

            }else{
                JOptionPane.showMessageDialog(null, "No Account Found,Contact the Manager");
            }
          
            }
        }else{
            JOptionPane.showMessageDialog(null, "Log In Failed");        
        }
    }//GEN-LAST:event_logInActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
        if(check.isSelected()){
            password.setEchoChar((char)0);
        }else{
            password.setEchoChar('*');
        }
        
    }//GEN-LAST:event_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logIn;
    public javax.swing.JPasswordField password;
    public javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
